In [3]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report, f1_score

In [17]:
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Cancer.csv')
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [5]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [6]:
y = df['diagnosis']
X = df.drop(['id','diagnosis','Unnamed: 32'],axis=1)
# Step 4 : train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)
# check shape of train and test sample
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((398, 30), (171, 30), (398,), (171,))

In [7]:
# Step 5 : select model
model = LogisticRegression(max_iter=5000)
# Step 6 : train or fit model
model.fit(X_train,y_train)

LogisticRegression(max_iter=5000)

In [8]:
model.intercept_


array([-29.71205302])

In [9]:
model.coef_


array([[-0.89911688, -0.18567461,  0.24542198, -0.02493933,  0.14004047,
         0.19248731,  0.4098653 ,  0.21929231,  0.172832  ,  0.03284183,
         0.00366523, -1.18227199, -0.19598744,  0.12488582,  0.02355691,
        -0.04994689,  0.01705431,  0.02869599,  0.03092407, -0.01428285,
        -0.25772506,  0.44390469,  0.17840819,  0.01163187,  0.28784332,
         0.59898918,  1.04778569,  0.44638254,  0.53258959,  0.07650395]])

In [10]:
y_pred = model.predict(X_test)
y_pred
#B for Benign (non-cancerous)
#M for Malignant (cancerous)

array(['B', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B',
       'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'M', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'M',
       'M', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B',
       'M', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M',
       'M', 'B', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'B'], dtype=object)

In [11]:
y_pred_proba = model.predict_proba(X_test)[:,1]
y_pred_proba.round(2)

array([0.14, 1.  , 0.99, 0.06, 1.  , 0.01, 1.  , 0.  , 1.  , 0.  , 0.03,
       0.72, 0.02, 1.  , 0.01, 0.  , 0.71, 0.  , 1.  , 0.03, 0.25, 0.  ,
       0.01, 0.01, 0.  , 1.  , 0.  , 0.02, 1.  , 0.  , 1.  , 0.  , 0.  ,
       0.  , 0.  , 1.  , 0.01, 0.  , 0.03, 0.82, 1.  , 0.99, 1.  , 1.  ,
       0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.03, 0.  , 0.  ,
       0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.01, 1.  , 1.  , 0.74,
       1.  , 0.  , 1.  , 0.78, 0.  , 0.52, 0.02, 0.96, 0.  , 1.  , 0.06,
       0.  , 1.  , 1.  , 0.99, 0.31, 0.01, 1.  , 1.  , 1.  , 0.05, 0.  ,
       0.42, 0.  , 0.99, 0.  , 0.13, 0.  , 0.76, 0.  , 0.99, 0.  , 0.22,
       1.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.02, 1.  , 0.01,
       0.  , 0.  , 1.  , 0.02, 0.  , 0.  , 0.  , 1.  , 0.  , 0.03, 1.  ,
       0.05, 1.  , 0.  , 1.  , 0.8 , 0.03, 0.  , 0.  , 1.  , 1.  , 0.  ,
       0.99, 0.99, 1.  , 0.03, 0.  , 0.6 , 0.  , 1.  , 0.  , 1.  , 0.2 ,
       1.  , 0.  , 1.  , 0.  , 0.05, 0.58, 0.  , 1.

In [12]:
# Helper fuctions to evaluate our model.
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
# Accuracy Score: 0.826816

print("Accuracy Score: %f" % accuracy)

Accuracy Score: 0.959064


In [13]:
mapping = {1: 'B', 0: 'M'}
# y_test and y_pred are initially in string form ('B', 'M')
y_test = [1 if label == 'B' else 0 for label in y_test]
y_pred = [1 if label == 'B' else 0 for label in y_pred]


precision = precision_score(y_test, y_pred)
print("Precision Score: %f" % precision)
print("In other words, when the model predicts someone survived, it is correct %f of the time." % precision)

Precision Score: 0.979798
In other words, when the model predicts someone survived, it is correct 0.979798 of the time.


In [14]:
recall = recall_score(y_test, y_pred)
print("Recall Score: %f" % recall)
print("In other words, it correctly identifies %f percent of all survivors" % recall)

Recall Score: 0.950980
In other words, it correctly identifies 0.950980 percent of all survivors


In [15]:
from sklearn.metrics import f1_score

# F1 Score
f1_score(y_test, y_pred)

0.9651741293532339

In [16]:
# Print the classification report for evaluation
print(classification_report(y_test, y_pred))

# Explanation of the output:

# - precision: Measures how many of the predicted positive cases were actually correct.
#    - For class "0" (Malignant), the model has a precision of 0.93, meaning that 93% of the predicted Malignant cases were correctly identified.
#    - For class "1" (Benign), the model has a precision of 0.98, meaning that 98% of the predicted Benign cases were correct.
#
# - recall: Measures how many of the actual positive cases were correctly identified by the model.
#    - For class "0" (Malignant), the model has a recall of 0.97, meaning that 97% of all the actual Malignant cases were correctly identified.
#    - For class "1" (Benign), the model has a recall of 0.95, meaning that 95% of all the actual Benign cases were correctly identified.
#
# - F1-score: The harmonic mean of precision and recall. A balanced measure that gives us an overall idea of the model's performance.
#    - The F1-score for Malignant (0) is 0.95, indicating a strong balance between precision and recall.
#    - The F1-score for Benign (1) is 0.97, indicating an even stronger balance for this class.
#
# - support: The number of actual instances of each class in the test set.
#    - Support for Malignant (0): 69 instances
#    - Support for Benign (1): 102 instances
#
# - accuracy: The overall percentage of correct predictions made by the model across all classes.
#    - The accuracy is 0.96 (96%), meaning the model correctly predicted 96% of all test samples.
#
# - macro avg: The average performance of the model, treating all classes equally, regardless of their support.
#    - The macro average for precision, recall, and F1-score is 0.96, indicating the model performs consistently across both classes.
#
# - weighted avg: The average performance of the model, giving more weight to the classes with more samples (in this case, Benign).
#    - The weighted average for precision, recall, and F1-score is also 0.96, showing that even with the class imbalance, the model performs well.


              precision    recall  f1-score   support

           0       0.93      0.97      0.95        69
           1       0.98      0.95      0.97       102

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171

